server:
    port: 9009
    

security:
  jwt:
    public-key: classpath:public.txt

spring:
    application:
        name: transaction-service
    datasource:
      url : jdbc:mysql://localhost:3306/transaction?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC
      username : root
      password : root
      initialization-mode : always
    jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL8Dialect
    jpa.hibernate.ddl-auto : create-drop
    security.user.name : root
    security.user.password: root
    

message:
 source:
  basename: classpath:message/message.properties
  use.code.as.default.message: true

 