server:
    port: 9007
    
spring:
    application:
        name: oauth-service
    datasource:
      url : jdbc:mysql://db-internet-bank:3306/oauth_login?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC
      username : root
      password : root
      initialization-mode : always
    jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL8Dialect
    jpa.hibernate.ddl-auto : none
    security.user.name : root
    security.user.password: root

message:
 source:
  basename: classpath:message/message.properties
  use.code.as.default.message: true



security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: letmein
    key-pair-alias: mytestkey
    key-pair-password: changeme
